from algopipe.registry import Registry, BaseModule

@Registry.register("DL_Algorithms",subcategory="Convolutional_NN")
class GoogLeNet(BaseModule):
    name = "GoogLeNet"
    description = "GoogLeNet (Inception v1) architecture for image classification"

    def get_imports(self):
        return [
            "import torch",
            "import torch.nn as nn",
            "import torch.nn.functional as F"
        ]
    
    def get_code(self, variable_name="model"):
        return (
            f"# GoogLeNet Architecture\n"
            f"class Inception(nn.Module):\n"
            f"    def __init__(self, in_channels, out1x1, out3x3red, out3x3, out5x5red, out5x5, pool_proj):\n"
            f"        super(Inception, self).__init__()\n"
            f"        self.branch1 = nn.Conv2d(in_channels, out1x1, kernel_size=1)\n"
            f"        self.branch2 = nn.Sequential(\n"
            f"            nn.Conv2d(in_channels, out3x3red, kernel_size=1),\n"
            f"            nn.Conv2d(out3x3red, out3x3, kernel_size=3, padding=1)\n"
            f"        )\n"
            f"        self.branch3 = nn.Sequential(\n"
            f"            nn.Conv2d(in_channels, out5x5red, kernel_size=1),\n"
            f"            nn.Conv2d(out5x5red, out5x5, kernel_size=5, padding=2)\n"
            f"        )\n"
            f"        self.branch4 = nn.Sequential(\n"
            f"            nn.MaxPool2d(kernel_size=3, stride=1, padding=1),\n"
            f"            nn.Conv2d(in_channels, pool_proj, kernel_size=1)\n"
            f"        )\n\n"
            f"    def forward(self, x):\n"
            f"        branch1 = F.relu(self.branch1(x))\n"
            f"        branch2 = F.relu(self.branch2(x))\n"
            f"        branch3 = F.relu(self.branch3(x))\n"
            f"        branch4 = F.relu(self.branch4(x))\n"
            f"        outputs = [branch1, branch2, branch3, branch4]\n"
            f"        return torch.cat(outputs, 1)\n\n"
            f"class GoogLeNet(nn.Module):\n"
            f"    def __init__(self, num_classes=1000):\n"
            f"        super(GoogLeNet, self).__init__()\n"
            f"        self.conv1 = nn.Conv2d(3, 64, kernel_size=7, stride=2, padding=3)\n"
            f"        self.maxpool1 = nn.MaxPool2d(kernel_size=3, stride=2, padding=1)\n"
            f"        self.conv2 = nn.Conv2d(64, 64, kernel_size=1)\n"
            f"        self.conv3 = nn.Conv2d(64, 192, kernel_size=3, padding=1)\n"
            f"        self.maxpool2 = nn.MaxPool2d(kernel_size=3, stride=2, padding=1)\n"
            f"        self.inception3a = Inception(192, 64, 96, 128, 16, 32, 32)\n"
            f"        self.inception3b = Inception(256, 128, 128, 192, 32, 96, 64)\n"
            f"        self.maxpool3 = nn.MaxPool2d(kernel_size=3, stride=2, padding=1)\n"
            f"        self.inception4a = Inception(480, 192, 96, 208, 16, 48, 64)\n"
            f"        self.inception4b = Inception(512, 160, 112, 224, 24, 64, 64)\n"
            f"        self.inception4c = Inception(512, 128, 128, 256, 24, 64, 64)\n"
            f"        self.inception4d = Inception(512, 112, 144, 288, 32, 64, 64)\n"
            f"        self.inception4e = Inception(528, 256, 160, 320, 32, 128, 128)\n"
            f"        self.maxpool4 = nn.MaxPool2d(kernel_size=3, stride=2, padding=1)\n"
            f"        self.inception5a = Inception(832, 256, 160, 320, 32, 128, 128)\n"
            f"        self.inception5b = Inception(832, 384, 192, 384, 48, 128, 128)\n"
            f"        self.avgpool = nn.AdaptiveAvgPool2d((1, 1))\n"
            f"        self.dropout = nn.Dropout(0.4)\n"
            f"        self.fc = nn.Linear(1024, num_classes)\n\n"
            f"    def forward(self, x):\n"
            f"        x = F.relu(self.conv1(x))\n"
            f"        x = self.maxpool1(x)\n"
            f"        x = F.relu(self.conv2(x))\n"
            f"        x = F.relu(self.conv3(x))\n"
            f"        x = self.maxpool2(x)\n"
            f"        x = self.inception3a(x)\n"
            f"        x = self.inception3b(x)\n"
            f"        x = self.maxpool3(x)\n"
            f"        x = self.inception4a(x)\n"
            f"        x = self.inception4b(x)\n"
            f"        x = self.inception4c(x)\n"
            f"        x = self.inception4d(x)\n"
            f"        x = self.inception4e(x)\n"
            f"        x = self.maxpool4(x)\n"
            f"        x = self.inception5a(x)\n"
            f"        x = self.inception5b(x)\n"
            f"        x = self.avgpool(x)\n"
            f"        x = x.view(x.size(0), -1)\n"
            f"        x = self.dropout(x)\n"
            f"        x = self.fc(x)\n"
            f"        return x\n\n"
            f"# Initialize model\n"
            f"{variable_name} = GoogLeNet(num_classes=1000)"
        )