from typing import List, Tuple
from algopipe.registry import BaseModule

class PipelineGenerator:
    def __init__(self):
        self.pipeline: List[BaseModule] = []

    def add_step(self, module: BaseModule):
        self.pipeline.append(module)

    def generate_code(self) -> str:
        all_imports = set()
        code_blocks = []

        
        for module in self.pipeline:
            all_imports.update(module.get_imports())
            code_blocks.append(module.get_code())

        
        imports_str = "\n".join(sorted(list(all_imports)))

        body_str = "\n\n".join(code_blocks)

        
        full_script = (
            f"# Generated by AI Tool\n"
            f"import pandas as pd\n"
            f"import numpy as np\n"
            f"{imports_str}\n\n"
            f"def main():\n"
            f"    # Load your data here (Placeholder)\n"
            f"    df = pd.read_csv('data.csv')\n\n"
            f"{self._indent_code(body_str)}\n\n"
            f"if __name__ == '__main__':\n"
            f"    main()"
        )
        return full_script

    def _indent_code(self, code: str, spaces=4) -> str:
        """Helper to indent the generated body code."""
        indentation = " " * spaces
        return "\n".join([f"{indentation}{line}" if line else line for line in code.split('\n')])