import json
from typing import List, Tuple
from algopipe.registry import BaseModule

class PipelineGenerator:
    def __init__(self):
        self.pipeline: List[BaseModule] = []

    def add_step(self, module: BaseModule):
        self.pipeline.append(module)

    def generate_code(self) -> str:
        """Generates a standard Python (.py) script."""
        all_imports = set()
        code_blocks = []

        for module in self.pipeline:
            all_imports.update(module.get_imports())
            code_blocks.append(module.get_code())

        imports_str = "\n".join(sorted(list(all_imports)))
        body_str = "\n\n".join(code_blocks)

        full_script = (
            f"# Generated by AlgoPipe\n"
            f"import pandas as pd\n"
            f"import numpy as np\n"
            f"{imports_str}\n\n"
            f"def main():\n"
            f"{self._indent_code(body_str)}\n\n"
            f"if __name__ == '__main__':\n"
            f"    main()"
        )
        return full_script

    def generate_notebook(self) -> dict:
        """Generates a Jupyter Notebook (.ipynb) JSON structure."""
        cells = []

        # 1. Title Markdown Cell
        cells.append({
            "cell_type": "markdown",
            "metadata": {},
            "source": ["# 🚀 AlgoPipe Generated ML Pipeline\n", "This notebook was automatically generated by AlgoPipe."]
        })

        # 2. Global Imports Cell
        all_imports = {"import pandas as pd", "import numpy as np"}
        for module in self.pipeline:
            all_imports.update(module.get_imports())

        cells.append({
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            # Add a newline to each import string for valid JSON array formatting
            "source": [line + "\n" for line in sorted(list(all_imports))]
        })

        # 3. Create a cell for each Pipeline Step
        for module in self.pipeline:
            # Safely get name and description (fallback to class name if missing)
            mod_name = getattr(module, 'name', module.__class__.__name__)
            mod_desc = getattr(module, 'description', '')

            # Markdown header for the step
            cells.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": [f"### {mod_name}\n", f"{mod_desc}"]
            })

            # Code for the step
            cells.append({
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [line + "\n" for line in module.get_code().split('\n')]
            })

        # 4. Construct the final Notebook JSON
        notebook = {
            "cells": cells,
            "metadata": {},
            "nbformat": 4,
            "nbformat_minor": 5
        }
        return notebook

    def _indent_code(self, code: str, spaces=4) -> str:
        """Helper to indent the generated body code."""
        indentation = " " * spaces
        return "\n".join([f"{indentation}{line}" if line else line for line in code.split('\n')])